### ISSUE TITLE
Expose our specific mtypes on SAMP WebProfile

### ISSUE THREAD

**Issue by gmella** [JMMC-OpenDev/jmcs#4]
All fr.jmmc.* capabilities are properly exposed  by jsamp hub accross local applications but not to the web profile.

A first workarround is to run a Hub using the following property:
JAVA_OPTIONS="-Djsamp.mtypes.safe=samp.app.*,samp.msg.progress,table.*,image.*,coord.*,spectrum.*,bibcode.*,voresource.*,fr.*"

A possible solution could be to define some (or every?) SampCapability with the x-samp.mostly-harmless key as proposed in https://wiki.ivoa.net/twiki/bin/view/IVOA/SampXSamp and covered by jsamp implementation.
In this case we could run Topcat, open OiDB and then send a collection to OIfitsExplorer.

http://astrojs.github.io/sampjs/examples/monitor.html may help to look at shared subs through the webprofile.

**Comment by bourgesl** [comment]
Should be fixed now in jmcs

**Comment by gmella** [comment]
Approved! Thx!
